//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by dvredit.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDB_30U                         30
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_DVREDIT_DIALOG              102
#define IDD_MPG2DVR                     103
#define IDC_SLIDE                       105
#define IDD_DEFAULTDECODER              106
#define ID_STATUSBAR                    107
#define IDC_STATUS_BAR                  108
#define IDD_METADATAEDITOR              109
#define IDR_MAINFRAME                   128
#define IDR_MENU1                       129
#define IDD_ATTRIBUTES_DIALOG           130
#define IDD_DVR2MPG                     131
#define PLAYU                           137
#define PLAYD                           138
#define IDB_BITMAP_TEMPLATEU            139
#define STOPU                           140
#define STOPD                           141
#define IDB_BITMAP_TEMPLATED            142
#define LOADU                           143
#define LOADD                           144
#define STEP_FORWARDU                   145
#define STEP_FORWARDD                   146
#define PLAYX                           150
#define STOPX                           153
#define STEP_FORWARDX                   155
#define STEP_BACKWARDU                  159
#define STEP_BACKWARDD                  160
#define STEP_BACKWARDX                  161
#define SEGMENT_PREVU                   163
#define SEGMENT_PREVD                   164
#define SEGMENT_PREVX                   165
#define SEGMENT_NEXTU                   166
#define SEGMENT_NEXTD                   167
#define SEGMENT_NEXTX                   168
#define SEGMENT_CLEARU                  169
#define SEGMENT_CLEARD                  170
#define SEGMENT_CLEARX                  171
#define INU                             172
#define IND                             173
#define INX                             174
#define OUTU                            175
#define OUTD                            176
#define OUTX                            177
#define IDB_30D                         178
#define IDB_30X                         179
#define SEGMENT_PLAYU                   180
#define SEGMENT_PLAYD                   181
#define STOPX1                          182
#define SAVEU                           182
#define SEGMENT_PLAYX                   183
#define IDR_ACCELERATOR                 183
#define SEGMENT_ENDU                    184
#define SEGMENT_ENDD                    185
#define IDD_REFERENCE2CONTENT           185
#define SEGMENT_ENDX                    186
#define IDD_COMBINERECORDINGS           186
#define SEGMENT_STARTU                  187
#define SEGMENT_STARTD                  188
#define SEGMENT_STARTX                  189
#define SAVED                           190
#define SAVEX                           191
#define IDC_BUTTON_PLAY                 1001
#define IDC_BUTTON_STOP                 1003
#define IDC_BUTTON_STEP_FORWARD         1004
#define IDC_SLIDER                      1006
#define IDC_BUTTON_COMMERCIAL_SKIP      1007
#define IDC_BUTTON_STEP_BACKWARD        1008
#define IDC_EDIT_SOURCE_FILE            1014
#define IDC_EDIT_DEST_FILE              1015
#define IDC_STATIC_SOURCE_LABEL         1016
#define IDC_STATIC_DEST_LABEL           1017
#define IDC_BUTTON_SOURCE_BROWSE        1018
#define IDC_BUTTON_DEST_BROWSE          1019
#define IDC_BUTTON_ATTRIBUTES           1020
#define IDC_STATIC_LABEL_AUTHOR         1021
#define IDC_STATIC_LABEL_TITLE          1022
#define IDC_STATIC_LABEL_COPYRIGHT      1023
#define IDC_STATIC_LABEL_DESCRIPTION    1024
#define IDC_STATIC_LABEL_RATING         1025
#define IDC_EDIT_AUTHOR                 1026
#define IDC_EDIT_COPYRIGHT              1027
#define IDC_EDIT_TITLE                  1028
#define IDC_EDIT_RATING                 1029
#define IDC_EDIT_SUBTITLE               1029
#define IDC_EDIT_DESCRIPTION            1030
#define IDC_EDIT_GENRE                  1031
#define IDC_EDIT_TITLE4                 1032
#define IDC_EDIT_MEDIACREDITS           1032
#define IDC_EDIT_REF_TIME               1037
#define IDC_BUTTON_IN                   1038
#define IDC_BUTTON_OUT                  1039
#define IDC_CLEAR                       1040
#define IDC_STATIC_SEGMENT_LABEL        1041
#define IDC_BUTTON_PREVIOUS_SEGMENT     1043
#define IDC_BUTTON_NEXT_SEGMENT         1044
#define IDC_BUTTON_PLAY_SEGMENT         1046
#define IDC_BUTTON_PLAY_ALL_SEGMENTS    1047
#define IDC_BUTTON_CLEAR_SEGMENT        1048
#define IDC_SEGMENT_NUMBER              1049
#define IDC_BUTTON_SEGMENT_START        1052
#define IDC_BUTTON_SEGMENT_END          1053
#define IDC_BUTTON_LOAD                 1054
#define IDC_BUTTON_SAVE                 1055
#define IDC_VERSION                     1056
#define IDC_STATIC_LABEL_SUBTITLE       1057
#define IDC_STATIC_LABEL_GENRE          1058
#define IDC_STATIC_LABEL_MEDIACREDITS   1059
#define IDC_EDIT_PROFILE                1063
#define IDC_BROWSE_SOURCE               1064
#define IDC_BROWSE_DEST                 1065
#define IDC_BUTTON3                     1066
#define IDC_BROWSE_PROFILE              1066
#define IDC_BROWSE_REFERENCE_RECORDING  1066
#define IDC_MONTHCALENDAR1              1067
#define IDC_LIST1                       1068
#define IDC_STATIC_MAILTO               1071
#define IDC_STATIC_TGB                  1072
#define IDC_STATIC_TGB_LABEL            1073
#define IDC_EDIT_CONTENT_RECORDING      1074
#define IDC_EDIT_REFERENCE_RECORDING    1075
#define IDC_BROWSE_CONTENT_RECORDING    1076
#define IDC_STATIC_REFERENCE_RECORDING  1078
#define IDC_STATIC_CONTENT_RECORDING    1079
#define IDC_LIST_COMBINE                1080
#define IDC_BUTTON_COMBINE_ADD          1081
#define IDC_BUTTON_COMBINE_REMOVE       1082
#define IDC_COMBO_VIDEO                 1085
#define IDC_COMBO_AUDIO                 1086
#define IDC_COMBO1                      1087
#define IDC_BUTTON2                     1089
#define IDC_EDIT1                       1090
#define IDC_COMBO2                      1091
#define IDC_EDIT2                       1093
#define ID_FILE_OPEN32771               32771
#define ID_FILE_SAVEAS                  32772
#define ID_FILE_EXIT                    32773
#define ID_TOOLS_DVRTOMPG               32774
#define ID_TOOLS_MPGTODVR               32775
#define ID_HELP_ABOUT                   32776
#define ID_ACCELERATOR_PAUSE            32777
#define ID_ACCELERATOR_PLAY             32778
#define ID_ACCELERATOR_RECORD           32779
#define ID_ACCELERATOR_BACK             32780
#define ID_ACCELERATOR_FORWARD          32781
#define ID_ACCELERATOR_STOP             32782
#define ID_TOOLS_DVRTOWMV               32784
#define ID_ACCELERATOR_IN1              32786
#define ID_ACCELERATOR_OUT1             32787
#define ID_ACCELERATOR_IN2              32789
#define ID_ACCELERATOR_OUT2             32790
#define ID_TOOLS_OPENREFERENCERECORDING 32792
#define ID_TOOLS_APPENDRECORDINGS       32793
#define ID_TOOLS_DUMPELEMENTARYSTREAMS  32794
#define ID_TOOLS_DEFAULTDECODERS        32795
#define ID_TOOLS_EDITMETADATA           32796

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        189
#define _APS_NEXT_COMMAND_VALUE         32797
#define _APS_NEXT_CONTROL_VALUE         1094
#define _APS_NEXT_SYMED_VALUE           109
#endif
#endif
